### ISSUE TITLE
Add Rocker to benchmark

### ISSUE THREAD

**Issue by zonaut** [jreijn/spring-comparing-template-engines#40] opened 2019-05-06 13:14 UTC
Rocker claims to outperform most of the template engines. It would be nice to see reproduced here.
https://github.com/fizzed/rocker

**Comment by Vest** [comment] 2019-05-06 13:26
Yes, looks interesting, but the thing is:
> The Rocker parser will generate a Java source file for each template.

I do not expect it to be (much) slower than JSP. If I can integrate the template engine into the Spring container, I will update the issue.

**Comment by zonaut** [comment] 2019-05-06 19:24
Yes, I would expect it to close to JSP also. Most benchmarks give me almost the same measured time. I am running these on a linux box so that seems to produce different (better) results in most cases.
For me the interesting part would be to see how much memory consumption there was while doing these benchmarks.

**Comment by Vest** [comment] 2019-05-07 14:22
I have updated the project recently with HtmlFlow. You can have a look at it, by the way.
Regarding the memory consumption, I cannot help you there. This project consumes over 1 GB just right after the start :) I am even considering about splitting it to smaller projects. Eventually many libraries are very old.
I will try to play with Rocket in the nearest... future... years :) No promises, as usual.

**Comment by Vest** [comment] 2019-05-09 13:38
The issue is resolved with PR #45. You can test it now.

Rocker is an inconvenient framework for testing, if you use Eclipse. Because it requires the template preprocessing, compiling etc.

**Closed by Vest** 2019-05-09 13:38 UTC
Labels: enhancement
